app:
  report:
    file:
      #上传对应本地全路径，目录必须是真实存在的，注意 Win是 \ 且有盘符，linux是 / 无盘符
      dist-path: ./workspace/report/export
      white-list: .png|.jpg|.jpeg|.gif|.icon|.pdf|.xlsx|.xls|.csv|.mp4|.avi
      excelSuffix: .xlsx|.xls|.csv
      #上传对应下载的下载链接路径 http://serverip:9095/file/download
      downloadPath: http://10.108.26.197:9095/file/download

    # 跳过token验证和权限验证的url清单
    skip-authenticate-urls: /gaeaDict/all, /login, /static, /file/download/, /index.html, /favicon.ico, /reportShare/detailByCode, /admin/, /report/viewAdd, /file/upload
    user:
      ##新增用户默认密码
      default:
        password: 123456

  module:
    report:
      debug: true
      vue: true
      rootResource: /META-INF/report-static/
      webUrlPrefix: /report/static/
      debugWebUrlPrefix: http://localhost:3100/#/
      name: "数据大屏"
      code: report
      ignore-self: true
      pages: []
      menus:
        - name: 数据管理与可视化
          code: manager
          sort: 10
          children:
            - name: 数据源管理
              code: datasource
              sort: 10
              path: report/datasource
            - name: 数据集管理
              code: dataset
              sort: 20
              path: report/resultset
            - name: 展板与报告管理
              code: dashboard
              sort: 30
              path: report/report
        - name: 展板与报告
          code: report
          sort: 20
          children:
            - name: 大屏列表
              code: dashboard
              sort: 10
              path: report/bigscreen
            - name: 报告列表
              code: report
              sort: 20
              path: report/excelreport
